carla:
  # host: '172.17.0.1'
  host: '172.30.37.29'
  port: 2000
  timeout: 50
  passive: False
  synchronous_mode: True
  synchronous_mode_wait_for_vehicle_control_command: False
  fixed_delta_seconds: 0.10
  register_all_sensors: True
  town: 'Town01'
  ego_vehicle:
    role_name: ["hero", "ego_vehicle"]
